
- name: Add NodeSource repo key
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
- name: Add NodeSource binary repo
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
    state: present

- name: Add NodeSource src repo
  apt_repository:
    repo: "deb-src https://deb.nodesource.com/node_{{ node_version }}.x {{ ansible_distribution_release }} main"
    state: present

- name: Installs nodejs
  apt:
    pkg: nodejs
    update_cache: yes
    state: fixed

- name: Install yarn
  community.general.npm:
    name: yarn
    global: yes
